name: publish ios manually

on: workflow_dispatch

jobs:
  publish_manually:
    name: Publish Manually
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run pub.dev/inject-credentials@shell
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          if [ -z $PUB_CACHE ];then
            PUB_CACHE=~/.pub-cache
          fi
          mkdir -p $PUB_CACHE
          echo $CREDENTIALS > $PUB_CACHE/credentials.json
      - run: flutter --version
      - run: cd alipay_kit_ios; flutter pub get
      - run: cd alipay_kit_ios; dart format --set-exit-if-changed .
      - run: cd alipay_kit_ios; echo "y" | flutter pub publish
